BLD: Building CSP core with ``meson``
zklaus/csp pull request #1
Opened 2024-06-11 16:52 UTC by czgdp1807

All the workarounds are removed except one, which is the renaming of Time.h file. Actually meson passes, `-I. -I..` to C++ compiler to make sure that the build dir and the source dir are added to the include paths. It causes shadowing of `time.h` file present in C++ standard library which leads to compilation errors. I discussed with Ralf (he and I work on meson usage in SciPy) and he told me that renaming is the best strategy here instead of editing include paths. Having files with the same name as in C++ standard library is not a nice practice according to me and Ralf.

2024-06-12 10:13 UTC, zklaus requested changes
It's great to have a working meson build for core!
I do have a few suggestions to improve it. Don't hesitate to challenge them :wink:

2024-06-12 10:13 UTC, zklaus commented on cpp/csp/core/BasicAllocator.h
> +#include <Platform.h>
I don't think this is a great option for the include directives. The difference between <> and "" includes is a bit murky because the standard leaves it all up to the compiler implementation, but roughly, <> should be used for system headers. This means that either the old form of `<csp/core/Platform.h>` is appropriate, or a new `"Platform.h"`, but `<Platform.h>` is confusing.

C.f. [GCC's implementation](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html), [the standard](https://en.cppreference.com/w/cpp/preprocessor/include), and [one of the many community discussions](https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename).

Clearly Point72 have made their choice, so my first intuition would be to stick with that. Probably it's enough to add `-I../../..` somewhere?

Of course this applies to all includes, but I'll comment only here.

2024-06-12 10:13 UTC, zklaus commented on cpp/csp/core/BasicAllocator.h
> +    //elemsize is size of a single alloc, blockSize is number of elements to
I know these trailing whitespaces are very annoying and it clearly is right to remove them. However, it makes reviewing a bit tedious and I am afraid that it will distract when it comes to making this PR upstream, so can we keep them for now? Perhaps we can just do a separate upstream PR to get rid of all trailing whitespace in one go?

2024-06-12 10:13 UTC, zklaus commented on cpp/csp/core/QueueWaiter.h
> +#include <Time_.h>
I'm not sure about this renaming. Sure, it's a good idea to avoid clashes with standard names. But looking at the list of header files here, many of them are so generic that clashes are likely, if not with the standard library, then with other libraries that happen to be installed. Here again the `<>` vs `""` distinction comes into play because `<>` favors system headers. Keeping the `csp/core` prefix in place is an effective means of namespacing the headers. The alternative `""` would find the local `Time.h` instead of anything installed by other libraries, which remains a risk for the other includes that happen not to have had any clashes *in your compilation environment*.

If we do go with renaming, I'd prefer a more expressive name, rather than a token distinctor. Good candidates seem to be `DateTime.h`, `TimeAndDate.h`, or similar.

2024-06-12 10:13 UTC, zklaus commented on cpp/csp/core/meson.build
> +    'c_std=c17',
If we have this, we should probably add `'c'` to the list of languages in line 3.

2024-06-12 10:13 UTC, zklaus commented on cpp/csp/core/meson.build
> +conf_data.set('CSP_VERSION_PATCH', PROJECT_VERSION_PATCH.stdout().strip())
Meson has a rather strong opinion on environment vars, see [this comment](https://github.com/mesonbuild/meson/issues/9#issuecomment-381410972).
I think circumventing it in this manner is not wise. Besides, we are already setting the version in this file in line 4, so we even risk inconsistent version numbers.

Let's just set the three `PROJECT_VERSION_*` vars at the top of the file (add an optional `..._POST`?) and use that both to compose the version argument in the project call and set the `CSP_*` vars.

2024-06-12 10:13 UTC, zklaus commented on cpp/csp/core/meson.build
> +core_source_files = [core_public_headers, 'Exception.cpp', 'Time.cpp']
Let's add line breaks to put every entry on its own line. I personally think that's more readable, thought that may be debatable. What is certainly true is that it improves future diffs where files may be added or removed.

2024-06-12 10:13 UTC, zklaus commented on cpp/csp/core/meson.build
> +core_source_files = [core_public_headers, 'Exception.cpp', 'Time.cpp']
I think the headers should not be part of the source list in general. I have not checked every header, but from a small sample, they seem to be well written and not contain code that should be in a compilation unit of its own.

2024-06-12 10:13 UTC, zklaus commented on cpp/csp/core/meson.build
> +    )
```suggestion
csp_core_lib = library(
    'csp_core',
    core_source_files,
    install: true,
    )
    
install_headers(core_public_headers, subdir: 'csp/core')
```

2024-06-12 16:04 UTC, czgdp1807 commented on cpp/csp/core/BasicAllocator.h
> +    //elemsize is size of a single alloc, blockSize is number of elements to
Yes. Sure. Actually in my VSCode settings it auto trims all the trailing white spaces and extra newlines at the end of the file (keeps only one newline). So these changes happen automatically when I save them. I will undo them after resetting the git changes here.

2024-06-18 10:39 UTC, czgdp1807 commented on cpp/csp/core/meson.build
> +conf_data.set('CSP_VERSION_PATCH', PROJECT_VERSION_PATCH.stdout().strip())
Yes. Actually, `CSP_VERSION_MAJOR`, `CSP_VERSION_MINOR`, and `CSP_VERSION_PATCH` are used in `cpp/csp/core/Config.h.in`, so I added here. 

> Let's just set the three PROJECT_VERSION_* vars at the top of the file (add an optional ..._POST?) and use that both to compose the version argument in the project call and set the CSP_* vars.

Makes sense. But for this I think we need to compose the version sort of dynamically. Something like, `{PROJECT_VERSION_MAJOR}_{PROJECT_VERSION_MINOR}_{PROJECT_VERSION_PATCH}`.

2024-06-18 10:43 UTC, zklaus commented on cpp/csp/core/meson.build
> +conf_data.set('CSP_VERSION_PATCH', PROJECT_VERSION_PATCH.stdout().strip())
I played around with this, but the call to `project` needs to come first and the version is not easily set dynamically.
Then again, the situation in cmake seems to be similar, which is why the `CSP_*` variables are essentially set from their cmake counterparts. Consequently, I came up with this:
```
PROJECT_VERSION = meson.project_version().split('.')

conf_data = configuration_data()
conf_data.set('CSP_VERSION_MAJOR', PROJECT_VERSION[0])
conf_data.set('CSP_VERSION_MINOR', PROJECT_VERSION[1])
conf_data.set('CSP_VERSION_PATCH', PROJECT_VERSION[2])
configure_file(input : 'Config.h.in',
               output : 'Config.h',
               configuration : conf_data)
```
where ultimately the version is taken from its specification in the `project` call.

2024-06-18 16:18 UTC, czgdp1807 commented on cpp/csp/core/meson.build
> +conf_data.set('CSP_VERSION_PATCH', PROJECT_VERSION_PATCH.stdout().strip())
Thanks. Looks nice. Pushed it in my recent commit.

2024-06-20 11:43 UTC, zklaus commented
Superseded by zklaus/csp#3.

2024-06-20 11:43 UTC, closed without merging